### ISSUE TITLE
spelling fixes

### ISSUE THREAD

**Issue by sapientN3T** [cengique/Temples_Of_The_Nagas#1]
Hi, I was reading through the cfg and noticed a few spelling mistakes.

1. "alters" should be spelled "altars"

2. "God" should always be spelled with lowercase g ("god") unless the name of the god is God, then it becomes a proper noun. Since his name is Argus, it should be lowercase g ("god").

**Comment by cengique** [comment]
Thanks, I fixed several spelling mistakes now.
